name: teamwork

on:
  pull_request:
  pull_request_review:
    types: [submitted, dismissed]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ensure this project runs
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEAMWORK_URI: "localhost"
          TEAMWORK_API_TOKEN: "test_api_token"
          AUTOMATIC_TAGGING: false
          BOARD_COLUMN_OPENED: "PR Open"
          BOARD_COLUMN_MERGED: "Ready to Test"
          BOARD_COLUMN_APPROVED: 'PR Approved'
          BOARD_COLUMN_CHANGES_REQUESTED: 'Changes Requested'
          BOARD_COLUMN_CLOSED: "Rejected"
